### PR TITLE
1823 Revise for correctness and enhanced autocomplete

### PR DESCRIPTION
**Pull request by mmikowski**
1823 Enhance QWE CLI Bookmark Utility

1. Support tag as a base for a path with autocomplete.
Example: 'qwe tag/dir1/dir2'
2. Support autocomplete in interactive mode.
3. Handle special tags '-' and '~' more correctly.
4. Escape tags for special characters for use with grep -E
5. Add support for paths with spaces

All options have been tested and verified.

### CODE REVIEW

**Comment by mmikowski** [comment]
Hi Ólafur:

Have you had a chance to try the updated qwe presented here yet? I think you might really like the improvements. If there is a reason you'd rather not merge this to the mainline, please let me know and I can fix it.

Cheers, Mike

**Comment by mmikowski** [comment]
Hi Ólafur: Bump :)

**Comment by mmikowski** [comment]
Hi Ólafur, could you accept this PR? We're getting a lot of publicity, and I'd like to direct people to your original upstream repo instead of our fork to give you credit. Please let me know if you see any issues with this. For example: https://www.youtube.com/watch?v=AsMBkSiso_c

**Comment by olafurw** [comment]
I'm sorry, I did not notice your pullrequest. Not sure why I didn't get emails about it. I've accepted it.

**Comment by mmikowski** [comment]
Thanks Olafurw!  Best wishes. I guess it was my turn not to see emails! :)

**Comment by olafurw** [comment]
Hey @mmikowski 

I've moved qwe to it's own repo https://github.com/olafurw/qwe and invited you as a collaborator. Felt that the tool is too nice and the work you've done so good that it deserves it's own area.

**Pull request merged**
