### PR TITLE
Visual enhancements. Touch .qwe.data at startup.

### PR DESCRIPTION
**Pull request by mmikowski**
Hi Olafur:

Here is an update touches the .qwe.data file on startup and adds some nice visual touches. I also gave you more prominent credit in the header.  As always, please use as you see fit.

Sincerely, Mike

### CODE REVIEW

**Comment by olafurw** [comment]
Again, brilliant :) Very happy to see this!

**Comment by mmikowski** [comment]
Hi Olaf, you are welcome!  In the interest of ease-of-use, I think just typing 'qwe' should probably list available tags and prompt you to select one. At the end we could add a note that says to use -h to see the help page. What do you think?

**Comment by mmikowski** [comment]
BTW, we are now distributing this with https://kfocus.org

**Comment by olafurw** [comment]
It's really cool that you're shipping it with kfocus, I'm honored. Seems my buddy Jason also likes it (according to the testimony part of the website)

Yeah I'm in favor of `$ qwe` showing you the list. So `$ qwe` being interactive but the other functionality staying the same. That seems fine.

We could also add `$ qwe -` in a similar way as `$ cd -` does but it would take you to the last bookmark place you used.

```
$ qwe docs // takes you to /home/user/docs for example
$ cd ..
$ cd ..
$ qwe - // back to /home/user/docs
```

**Comment by mmikowski** [comment]
Great ideas Olaf.  I'll create a ticket to get this done. It may be a few days though :)

**Pull request merged**
